name: fauna_db_actions
description: Github action for automating Fauna databases. 
author: Fauna Labs
branding:
  icon: 'database'
  color: 'purple'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '20.x'
  fauna-secret-key:
    description: 'Secret key for Fauna DB'
    required: true

outputs:
  test-result:
    description: 'The result of the test run'

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Install Fauna CLI
      run: npm install -g fauna-shell

    - name: Push schema to Database
      run: fauna schema push --force --secret ${{ inputs.fauna-secret-key }}

    - name: Run tests
      run: npm test
      id: test
      continue-on-error: true

    - name: Reset Test Database
      run: fauna schema push --dir=./cleanup/ --force --secret ${{ inputs.fauna-secret-key }}

    - name: Set Test Result Output
      if: steps.test.outcome == 'success'
      run: echo "::set-output name=test-result::success"
      if: steps.test.outcome != 'success'
      run: echo "::set-output name=test-result::failure"
